version: '3.8'

services:
  api:
    image: ${OTOPS_PROFILE_API_DOCKER_IMAGE_NAME}:${OTOPS_PROFILE_API_DOCKER_IMAGE_TAG}
    container_name: ot-api
    ports:
      - "8090:8080"
    depends_on:
      - clickhouse
      - elasticsearch
    environment:
      SLICK_CLICKHOUSE_URL: "jdbc:clickhouse://clickhouse:8123"
      ELASTICSEARCH_HOST: "elasticsearch"
      META_APIVERSION_MAJOR: "0"
      META_APIVERSION_MINOR: "0"
      META_APIVERSION_PATCH: "0"
      META_DATA_YEAR: "23"
      META_DATA_MONTH: "6"
      META_DATA_ITERATION: "0"
      PLATFORM_API_IGNORE_CACHE: "true"
    networks:
      - ot-platform

  clickhouse:
    image: ${OTOPS_PROFILE_CLICKHOUSE_DOCKER_IMAGE_NAME}:${OTOPS_PROFILE_CLICKHOUSE_DOCKER_IMAGE_TAG}
    container_name: ot-ch
    ports:
      - "9000:9000"
      - "8123:8123"
    volumes:
      - "chconf:/etc/clickhouse-server/config.d"
      - "chusers:/etc/clickhouse-server/users.d"
      - "chdata:/var/lib/clickhouse"
    ulimits:
      nofile: 262144
    networks:
      - ot-platform

  elasticsearch:
    image: ${OTOPS_PROFILE_ELASTIC_SEARCH_DOCKER_IMAGE_NAME}:${OTOPS_PROFILE_ELASTIC_SEARCH_DOCKER_IMAGE_TAG}
    container_name: ot-es
    ports:
      - "9200:9200"
      - "9300:9600"
    environment:
      - "path.data=/usr/share/opensearch/data"
      - "path.logs=/usr/share/opensearch/logs"
      - "cluster.name=ot-es-cluster"
      - "network.host=0.0.0.0"
      - "discovery.type=single-node"
      - "discovery.seed_hosts=[]"
      - "bootstrap.memory_lock=true"
      - "search.max_open_scroll_context=5000"
      - "DISABLE_SECURITY_PLUGIN=true"
      - "logger.level=DEBUG"
      - "OPENSEARCH_JAVA_OPTS=-Xms2g -Xmx4g"
    volumes:
      - "esdata:/usr/share/opensearch/data"
    ulimits:
      memlock: -1
      nofile: 65536
    healthcheck:
      test: ["CMD", "curl", "http://localhost:9200/_cluster/health?wait_for_status=green"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s
    networks:
      - ot-platform

  nginx:
    image: ${OTOPS_PROFILE_NGINX_DOCKER_IMAGE_NAME}:${OTOPS_PROFILE_NGINX_DOCKER_IMAGE_TAG}
    ports:
      - "8080:8080"
    volumes:
      - "webapp:/srv/site"
      - "${OTOPS_PATH_CONFIG_WEBAPP}/nginx.conf:/etc/nginx/conf.d/default.conf"
    networks:
      - ot-platform

  openai:
    image: ${OTOPS_PROFILE_OPENAI_API_DOCKER_IMAGE_NAME}:${OTOPS_PROFILE_OPENAI_API_DOCKER_IMAGE_TAG}
    container_name: ot-ai-api
    ports:
      - 8081:8080 
    environment:
      OPENAI_TOKEN: ${OTOPS_PROFILE_OPENAI_TOKEN}
    networks:
      - ot-platform

networks:
  ot-platform:
    name: ot_platform


volumes:
  esdata:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: "${OTOPS_PATH_DEPLOYMENT_ELASTIC_SEARCH}/data"
  chconf:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: "${OTOPS_PATH_DEPLOYMENT_CLICKHOUSE}/config.d"
  chusers:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: "${OTOPS_PATH_DEPLOYMENT_CLICKHOUSE}/users.d"
  chdata:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: "${OTOPS_PATH_DEPLOYMENT_CLICKHOUSE}/data"
  webapp:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: "${OTOPS_PATH_DEPLOYMENT_WEBAPP}"