version: '3.8'

services:
  api:
    image: ${OTOPS_PROFILE_API_DOCKER_IMAGE_NAME}:${OTOPS_PROFILE_API_DOCKER_IMAGE_TAG}
    container_name: ot-api
    ports:
      - "8090:8080"
    depends_on:
      - clickhouse
      - elasticsearch
    environment:
      SLICK_CLICKHOUSE_URL: "jdbc:clickhouse://clickhouse:8123"
      ELASTICSEARCH_HOST: "elasticsearch"
      META_APIVERSION_MAJOR: "0"
      META_APIVERSION_MINOR: "0"
      META_APIVERSION_PATCH: "0"
      META_DATA_YEAR: "23"
      META_DATA_MONTH: "6"
      META_DATA_ITERATION: "0"
    networks:
      - ot-platform

  clickhouse:
    image: ${OTOPS_PROFILE_CLICKHOUSE_DOCKER_IMAGE_NAME}:${OTOPS_PROFILE_CLICKHOUSE_DOCKER_IMAGE_TAG}
    container_name: ot-ch
    ports:
      - "9000:9000"
      - "8123:8123"
    volumes:
      - "${OTOPS_PATH_DEPLOYMENT_CLICKHOUSE}/config.d:/etc/clickhouse-server/config.d"
      - "${OTOPS_PATH_DEPLOYMENT_CLICKHOUSE}/users.d:/etc/clickhouse-server/users.d"
      - "${OTOPS_PATH_DEPLOYMENT_CLICKHOUSE}/data:/var/lib/clickhouse"
    ulimits:
      nofile: 262144
    networks:
      - ot-platform

  elasticsearch:
    image: ${OTOPS_PROFILE_ELASTIC_SEARCH_DOCKER_IMAGE_NAME}:${OTOPS_PROFILE_ELASTIC_SEARCH_DOCKER_IMAGE_TAG}
    container_name: ot-es
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "path.data=/usr/share/elasticsearch/data"
      - "path.logs=/usr/share/elasticsearch/logs"
      - "cluster.name=ot-es-cluster"
      - "network.host=0.0.0.0"
      - "discovery.type=single-node"
      - "discovery.seed_hosts=[]"
      - "bootstrap.memory_lock=true"
      - "search.max_open_scroll_context=5000"
    volumes:
      - "esdata:/usr/share/elasticsearch/data"
    ulimits:
      memlock: -1
      nofile: 65536
    networks:
      - ot-platform

  nginx:
    image: ${OTOPS_PROFILE_NGINX_DOCKER_IMAGE_NAME}:${OTOPS_PROFILE_NGINX_DOCKER_IMAGE_TAG}
    ports:
      - "8080:8080"
    volumes:
      - "${OTOPS_PATH_DEPLOYMENT_WEBAPP}:/srv/site"
      - "${OTOPS_PATH_CONFIG_WEBAPP}/nginx.conf:/etc/nginx/conf.d/default.conf"
    networks:
      - ot-platform

networks:
  ot-platform:

volumes:
  esdata:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: "${OTOPS_PATH_DEPLOYMENT_ELASTIC_SEARCH}/data"
